# Generated by Django 3.2.9 on 2022-07-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20211006_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='test_name',
            field=models.CharField(default=0.1168831168831169, max_length=255, verbose_name='Test Name'),
            preserve_default=False,
        ),
    ]
