# Generated by Django 3.2.9 on 2022-07-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_contact_test_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='contact_first_name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='test_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Test Name'),
        ),
    ]
