# Generated by Django 3.2.9 on 2022-07-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20220719_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='secondary_email',
        ),
    ]
