# Generated by Django 3.2.9 on 2022-07-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_remove_contact_secondary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
    ]
