# Generated by Django 3.2.9 on 2022-07-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_auto_20211022_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='first_name',
            new_name='contact_first_name',
        ),
    ]
