# Generated by Django 3.2.9 on 2022-07-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_rename_first_name_lead_contact_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='contact_first_name',
            new_name='first_name',
        ),
    ]
