# Generated by Django 3.2.9 on 2022-07-22 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0039_auto_20220202_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test name')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('organization', models.CharField(max_length=255, null=True, verbose_name='Organization')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.org')),
            ],
        ),
    ]
