# Generated by Django 3.2.9 on 2022-07-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_module',
            old_name='date_of_birth',
            new_name='date',
        ),
    ]
