# Generated by Django 3.2.9 on 2022-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0003_auto_20220723_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_module',
            name='mobilenumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
