# Generated by Django 3.2.9 on 2022-07-26 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_rename_contact_first_name_contact_first_name'),
        ('test_module', '0004_alter_test_module_mobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_module',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='contacts.contact'),
        ),
    ]
