# Generated by Django 3.2.9 on 2022-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0006_alter_test_module_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_module',
            name='contactname',
            field=models.CharField(max_length=255, null=True, verbose_name='contactname'),
        ),
    ]
