# Generated by Django 3.2.9 on 2022-07-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0007_test_module_contactname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_module',
            name='contactname',
        ),
    ]
